function createfigure(X1, Y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 14-Jun-2009 13:35:45

% Create figure
figure1 = figure('XVisual',...
   '0x24 (TrueColor, depth 15, RGB mask 0x7c00 0x03e0 0x001f)');

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on');
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Color',[0 0 1]);

% Create xlabel
xlabel({'Mile Post'});

% Create ylabel
ylabel({'Degree of Curvature'});

% Create title
title({'CSX Ohio River GRMS Alinement'});

